// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/mcps/check.ts";
import * as $$$$$$$$$1 from "./actions/mcps/configure.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/grain.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/resend.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/slack.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/stability.ts";
import * as $$$$$$$$$$$5 from "./apps/deco/tiptap-cloud.ts";
import * as $$$$$$$$$$$6 from "./apps/deco/vertex.ts";
import * as $$$$$$$$$$$7 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$8 from "./apps/site.ts";
import * as $$$0 from "./loaders/mcps/get.ts";
import * as $$$1 from "./loaders/mcps/search.ts";
import * as $$$$$$0 from "./sections/Component.tsx";
import * as $$$$$$1 from "./sections/Home.tsx";
import * as $$$$$$2 from "./sections/PDP.tsx";
import * as $$$$$$3 from "./sections/PDPResults.tsx";

const manifest = {
  "loaders": {
    "site/loaders/mcps/get.ts": $$$0,
    "site/loaders/mcps/search.ts": $$$1,
  },
  "sections": {
    "site/sections/Component.tsx": $$$$$$0,
    "site/sections/Home.tsx": $$$$$$1,
    "site/sections/PDP.tsx": $$$$$$2,
    "site/sections/PDPResults.tsx": $$$$$$3,
  },
  "actions": {
    "site/actions/mcps/check.ts": $$$$$$$$$0,
    "site/actions/mcps/configure.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/grain.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/resend.ts": $$$$$$$$$$$2,
    "site/apps/deco/slack.ts": $$$$$$$$$$$3,
    "site/apps/deco/stability.ts": $$$$$$$$$$$4,
    "site/apps/deco/tiptap-cloud.ts": $$$$$$$$$$$5,
    "site/apps/deco/vertex.ts": $$$$$$$$$$$6,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$7,
    "site/apps/site.ts": $$$$$$$$$$$8,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
