name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deco Deploy
        uses: deco-cx/deploy@v0.1.7-beta.1
        with:
          build_cmd: "deno run -A dev.ts build --unstable-kv"

      - name: Publish Apps
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: deno run -A ./scripts/publish.ts
        env:
          DECO_TOKEN: ${{ secrets.DECO_TOKEN }}
          WORKSPACE: /shared/deco.cx
